import type { PokemonType } from '../models/types'

/** Primary types for species used in wild/trainer/boss pools (Gen 1 focus). */
export const SPECIES_TYPES: Record<number, PokemonType[]> = {
  2: ['grass', 'poison'],
  5: ['fire'],
  8: ['water'],
  16: ['normal', 'flying'],
  19: ['normal'],
  21: ['normal', 'flying'],
  23: ['poison'],
  25: ['electric'],
  27: ['ground'],
  29: ['poison'],
  30: ['poison'],
  32: ['poison'],
  33: ['poison'],
  35: ['fairy'],
  37: ['fire'],
  39: ['normal', 'fairy'],
  41: ['poison', 'flying'],
  42: ['poison', 'flying'],
  43: ['grass', 'poison'],
  44: ['grass', 'poison'],
  45: ['grass', 'poison'],
  46: ['bug', 'grass'],
  47: ['grass', 'poison'],
  48: ['bug', 'poison'],
  49: ['bug', 'poison'],
  50: ['ground'],
  52: ['normal'],
  53: ['normal'],
  54: ['water'],
  55: ['water'],
  56: ['fighting'],
  57: ['fighting'],
  58: ['fire'],
  60: ['water'],
  61: ['water'],
  63: ['psychic'],
  64: ['psychic'],
  66: ['fighting'],
  67: ['fighting'],
  69: ['grass', 'poison'],
  70: ['grass', 'poison'],
  73: ['water', 'poison'],
  74: ['rock', 'ground'],
  75: ['rock', 'ground'],
  77: ['fire'],
  79: ['psychic'],
  81: ['electric', 'steel'],
  82: ['electric', 'steel'],
  84: ['normal', 'flying'],
  85: ['normal', 'flying'],
  86: ['water'],
  88: ['poison'],
  89: ['poison'],
  93: ['ghost', 'poison'],
  95: ['rock', 'ground'],
  96: ['psychic'],
  97: ['psychic'],
  98: ['water'],
  99: ['water'],
  100: ['electric'],
  101: ['electric'],
  105: ['ground'],
  106: ['fighting'],
  107: ['fighting'],
  109: ['poison'],
  110: ['poison'],
  111: ['ground', 'rock'],
  112: ['ground', 'rock'],
  114: ['grass'],
  118: ['water'],
  123: ['bug', 'flying'],
  125: ['electric'],
  126: ['fire'],
  127: ['bug'],
  133: ['normal'],
  147: ['dragon'],
  152: ['grass'],
  155: ['fire'],
  158: ['water'],
  172: ['electric'],
  175: ['fairy'],
  179: ['electric'],
  187: ['grass', 'flying'],
  194: ['water', 'ground'],
  203: ['psychic'],
  215: ['dark', 'ice'],
  220: ['ice', 'ground'],
  228: ['dark', 'fire'],
}

export function getSpeciesTypes(speciesId: number): PokemonType[] {
  return SPECIES_TYPES[speciesId] ?? ['normal']
}
